import type { Metadata } from "next";
import "./globals.css";
import { yekan } from "@/utils/fonts";
import ReactQueryProvider from "@/utils/providers/ReactQueryProvider";
import Layout from "@/components/layout/userLayout/Layout";
import TopLoader from "@/utils/providers/TopLoader";
import OrderReduxProvider from "@/utils/providers/ReduxProvider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html dir="rtl" lang="fa">
      <body className={yekan.className}>
        <TopLoader />
        <OrderReduxProvider>
          <ReactQueryProvider>
              <Layout> 
                {children}
              </Layout>
          </ReactQueryProvider>
        </OrderReduxProvider>

        </body>
    </html>
  );
}
